language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '8'
after_success:
  - npm i -g coveralls codeclimate-test-reporter
  - coveralls < coverage/lcov.info
  - codeclimate-test-reporter < coverage/lcov.info
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
